[build]
  # The directory containing your Next.js project (only needed if it's not the root folder)
  base = "papertrade"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
